name: aunty_rafiki
description: A new Flutter project.
 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
 
  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  # firebase_crashlytics: ^2.0.1
  cloud_firestore: ^1.0.6
  cloud_functions: ^1.0.4
  firebase_storage: ^8.0.4
  firebase_messaging: ^9.1.2
  firebase_remote_config: ^0.3.1+1
  firebase_analytics: ^8.0.1
  firebase_database: ^6.1.2
  firebase_dynamic_links: ^2.0.1
  firebase_in_app_messaging: ^0.5.0+1
  firebase_performance: ^0.7.0+1
  # flutter_local_notifications: ^5.0.0+1
  intl_phone_field: ^2.0.0
  provider: ^5.0.0
  timeline_tile: ^2.0.0
  intl: ^0.17.0
  time_formatter: ^1.0.0+5
  table_calendar: ^3.0.0
  date_time_picker: ^2.0.0
  pin_code_fields: ^7.0.0
  url_launcher: ^6.0.3
  flutter_launcher_icons: ^0.9.0
  font_awesome_flutter: ^9.0.0
  multi_image_picker: ^4.8.00
  google_fonts: ^2.0.0
  showcaseview: ^1.0.0
  transparent_image: ^2.0.0
  smooth_page_indicator: ^0.2.3
  shared_preferences: ^2.0.5
  enum_to_string: ^2.0.1
  badges: ^1.2.0
  file: ^6.1.0
  path_provider: ^2.0.1
  file_picker: ^3.0.1
  splashscreen: ^1.3.5
  easy_localization: ^3.0.0
  image_picker: ^0.7.4
  emoji_picker: ^0.0.2
  share: ^2.0.1
  cached_network_image: ^3.0.0
  numberpicker: ^2.1.1
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/aunty_rafiki.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/access/
    - assets/images/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
