name: aunty_rafiki
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_crashlytics: ^0.2.1
  cloud_firestore: ^0.14.1+1
  firebase_storage: ^5.0.0-dev.3
  intl_phone_field: ^1.4.2
  provider: ^4.3.2+2
  timeline_tile: ^1.0.0
  intl: ^0.16.1
  time_formatter: ^1.0.0
  video_player: ^0.11.0
  audioplayers: ^0.16.1
  table_calendar: ^2.2.3
  date_time_picker: ^1.0.2
  image_picker: ^0.6.7+11

  pin_code_fields: ^5.0.1
  flutter_launcher_icons: ^0.8.1
  font_awesome_flutter: ^8.8.1
  multi_image_picker: ^4.7.14
  google_fonts: ^1.1.1
  flutter_tts: ^1.3.0
  showcaseview: ^0.1.6
  transparent_image: ^1.0.0
  smooth_page_indicator: ^0.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/aunty_rafiki.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/access/
    - assets/baby/
    - assets/food/
    - assets/chats/
    - assets/images/gif/
    - assets/background.png
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
