name: aunty_rafiki
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.3
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.1"
  firebase_crashlytics: "^0.4.0+1"
  cloud_firestore: "^0.16.0+1"
  cloud_functions: "^0.9.0"
  firebase_storage: "^7.0.0"
  firebase_messaging: ^8.0.0-dev.14
  firebase_remote_config: "^0.6.0"
  firebase_analytics: "^7.0.1"
  firebase_database: "^6.0.0"
  firebase_dynamic_links: "^0.7.0+1"
  firebase_in_app_messaging: "^0.3.0+1"
  firebase_performance: "^0.5.0+1"
  flutter_local_notifications: ^4.0.1+1
  
  intl_phone_field: 1.4.2
  provider: 4.3.2+2
  timeline_tile: 1.0.0
  intl: any
  time_formatter: ^1.0.0
  video_player: 0.11.0
  table_calendar: 2.2.3
  date_time_picker: 1.0.2
  url_launcher: any
  pin_code_fields: 5.0.1
  flutter_launcher_icons: 0.8.1
  font_awesome_flutter: 8.8.1
  multi_image_picker: 4.7.14
  google_fonts: 1.1.1
  showcaseview: 0.1.6
  transparent_image: 1.0.0
  smooth_page_indicator: 0.2.0
  shared_preferences: 0.5.10
  enum_to_string: 1.0.11
  numberpicker: 1.3.0
  sqflite: 1.3.1+1
  badges: 1.1.1
  file: 5.2.1
  path_provider: 1.6.27
  file_picker: 2.1.5+1
  splashscreen: 1.3.5
  easy_localization: any
  flutter_image_compress: 0.7.0
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+22
  emoji_picker: ^0.1.0
  share: ^0.6.4+3
  fluttertoast: ^7.0.2
  cached_network_image: ^2.3.1
  photo_view: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/aunty_rafiki.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/access/
    - assets/images/
    - assets/
 