name: aunty_rafiki
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.1"
  firebase_crashlytics: "^0.4.0+1"
  cloud_firestore: "^0.16.0+1"
  cloud_functions: "^0.9.0"
  firebase_storage: "^7.0.0"
  firebase_messaging: ^8.0.0-dev.14
  firebase_remote_config: "^0.6.0"
  firebase_analytics: "^7.0.1"
  firebase_database: "^6.0.0"
  firebase_dynamic_links: "^0.7.0+1"
  firebase_in_app_messaging: "^0.3.0+1"
  firebase_performance: "^0.5.0+1"
  flutter_local_notifications: ^4.0.1+1
  
  intl_phone_field: ^1.4.4
  provider: ^5.0.0
  timeline_tile: ^2.0.0
  intl: any
  time_formatter: ^1.0.0
  video_player: ^2.1.0
  table_calendar: ^2.3.3
  date_time_picker: any
  url_launcher: any
  pin_code_fields: ^7.0.0
  flutter_launcher_icons: 0.8.1
  font_awesome_flutter: ^9.0.0
  multi_image_picker: ^4.8.00
  google_fonts: ^1.1.2
  showcaseview: 0.1.6
  transparent_image: ^2.0.0
  smooth_page_indicator: ^0.2.3
  shared_preferences: ^0.5.12+4
  enum_to_string: ^2.0.1
  sqflite: ^2.0.0+3
  badges: ^1.2.0
  file: ^6.1.0
  path_provider: ^1.6.28
  file_picker: ^2.1.7
  splashscreen: 1.3.5
  easy_localization: any
  flutter_image_compress: ^1.0.0
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+22
  emoji_picker: ^0.1.0
  share: ^2.0.1
  fluttertoast: ^8.0.3
  cached_network_image: ^2.3.1
  numberpicker: ^2.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/aunty_rafiki.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/access/
    - assets/images/
    - assets/
 